import Foundation

/// Natrium.swift
/// Autogenerated by Natrium
///
/// - see: https://github.com/e-sites/Natrium

enum Natrium {

    enum Environment: String {
        case development = "Development"
        case production = "Production"
        case staging = "Staging"
    }

    enum Configuration: String {
        case debug = "Debug"
        case release = "Release"
    }

    enum Config {
        static let configuration: Configuration = .debug
        static let environment: Environment = .development

        static let appID: String = "60c6fbeb4b93ac653c492ba806fc346d"
        static let openWeatherMapAPI: String = "https://api.openweathermap.org"
        static let openWeatherMapImage: String = "https://openweathermap.org/img/wn/"
    }
}